
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_fornecedor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka