
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
#  cloud:
#    config:
#      uri: http://localhost:8888
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka